# Generated by Django 5.2.5 on 2026-05-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='organization',
        ),
    ]
