# Generated by Django 5.2.5 on 2026-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='reconciliation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
