# Generated by Django 5.2.5 on 2026-08-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesAgentProfile',
        ),
    ]
