# Generated by Django 5.2.5 on 2026-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
