# Generated by Django 5.2.5 on 2026-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_mpesa_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform', True)), fields=('is_platform',), name='only_one_platform_organization'),
        ),
    ]
