# Generated by Django 5.2.5 on 2026-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_platform_access_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccesslog',
            name='actor_is_platform',
            field=models.BooleanField(default=False),
        ),
    ]
