# Generated by Django 4.2.6 on 2025-08-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("pricing", "0001_initial"),
        ("products", "0003_remove_product_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelistitem",
            name="product_variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricelist_items",
                to="products.productvariation",
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricelistitem",
            unique_together={("pricelist", "product_variation")},
        ),
    ]
