# Generated by Django 5.2.5 on 2026-05-11 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_items', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('pricelist', 'product')},
        ),
    ]
