# Generated by Django 5.2.5 on 2026-08-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricelistitem_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['-created_at']},
        ),
    ]
