# Generated by Django 5.2.5 on 2026-08-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_location_is_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentInventoryItem',
        ),
    ]
