# Generated by Django 4.2.6 on 2025-08-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_cost_price_and_more"),
        ("inventory", "0004_agentinventoryitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="stocktakeitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="product_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariation",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariation",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="product_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("product_variation", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="stocktakeitem",
            unique_together={("stock_take", "product_variation")},
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stocktakeitem",
            name="product",
        ),
    ]
