# Generated by Django 4.2.6 on 2025-08-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_unique_together_and_more'),
        ('products', '0003_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
