# Generated by Django 5.2.5 on 2025-08-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationrole",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="organization.organization",
            ),
        ),
    ]
