# Generated by Django 4.2.6 on 2025-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_saleitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="total_amount",
        ),
    ]
