# Generated by Django 5.2.5 on 2026-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_product_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('FAILED', 'Failed'), ('AWAITING_DIRECT_PAYMENT', 'Awaiting Direct Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=30),
        ),
    ]
