# Generated by Django 4.2.6 on 2025-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_remove_sale_total_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentInventoryItem',
        ),
    ]