# Generated by Django 5.2.5 on 2026-04-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_tags"),
        ("sales", "0005_remove_agentinventoryitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="product_variation",
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PAID", "Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                default="409ad24c-62b5-4bbe-931e-6c7f02b373eb",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="size_variation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "Extra Small"),
                    ("s", "Small"),
                    ("m", "Medium"),
                    ("l", "Large"),
                    ("xl", "Extra Large"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
