# Generated by Django 5.2.5 on 2026-04-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_tags"),
        ("sales", "0006_remove_saleitem_product_variation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.product",
            ),
        ),
    ]
