# Generated by Django 5.2.5 on 2026-04-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_saleitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
