# Generated by Django 5.2.5 on 2026-05-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_sale_shipping_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="organization",
        ),
    ]
