# Generated by Django 5.2.5 on 2026-05-11 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_remove_sale_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
