# Generated by Django 5.2.5 on 2026-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_saleitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('FAILED', 'Failed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
