# Generated by Django 4.2.6 on 2025-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_productvariation_unit_of_measure_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariation",
            name="name",
        ),
        migrations.AddField(
            model_name="productvariation",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xl", "Extra Large"),
                    ("l", "Large"),
                    ("m", "Medium"),
                    ("s", "Small"),
                    ("xs", "Extra Small"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
