# Generated by Django 4.2.6 on 2025-08-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_productvariation_name_productvariation_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reorder_level",
        ),
        migrations.AddField(
            model_name="productvariation",
            name="barcode",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="productvariation",
            name="reorder_level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
