# Generated by Django 5.2.5 on 2025-08-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0006_remove_product_barcode_remove_product_reorder_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
